config/routes.rb
Test3::Application.routes.draw do

  resources :auctions do
     resources :parcels
  end

  match 'destroy_all_auctions' => 'auctions#destroy_all'

  devise_for :users

  devise_for :installs

  
  root :to => "home#index"

    
  
  

end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
  
  belongs_to :auction
  has_one :zillow_parcel
  attr_accessible :address, :city, :country, :latitude, :longitude, :minimum_bid, :number, :state, :zip, :auction_id
  
  def full_address
    "#{address}, #{city}, #{state}"
  end
  
  def gmaps4rails_address
    "#{address}, #{city}, #{state}"
  end
  
 geocoded_by :full_address
 
 after_validation :geocode
 
 acts_as_gmappable
end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
  # GET /parcels
  # GET /parcels.json
  before_filter :get_auction
  
  def get_auction
    @auction = Auction.find(params[:auction_id])
  end
  
  
  def index
    @parcels = @auction.parcels
    @json = @parcels.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parcels }
    end
  end

  # GET /parcels/1
  # GET /parcels/1.json
  def show
    
    @parcel = @auction.parcels.find(params[:id])
    
    @json = @parcel.to_gmaps4rails
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parcel }
    end
  end

  # GET /parcels/new
  # GET /parcels/new.json
  def new
    @parcel = @auction.parcels.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @parcel }
    end
  end

  # GET /parcels/1/edit
  def edit
    @parcel = @auction.parcels.find(params[:id])
  end

  # POST /parcels
  # POST /parcels.json
  def create
    @parcel = @auction.parcels.new(params[:parcel])

    respond_to do |format|
      if @parcel.save
        format.html { redirect_to @parcel, notice: 'Parcel was successfully created.' }
        format.json { render json: @parcel, status: :created, location: @parcel }
      else
        format.html { render action: "new" }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parcels/1
  # PUT /parcels/1.json
  def update

    @parcel = @auction.parcels.find(params[:id])

    respond_to do |format|
      if @parcel.update_attributes(params[:parcel])
        format.html { redirect_to [@auction, @parcel], notice: 'Parcel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parcels/1
  # DELETE /parcels/1.json
  def destroy
    @parcel = @auction.parcels.find(params[:id])
    @parcel.destroy

    respond_to do |format|
      format.html { redirect_to auction_parcels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/parcels_helper.rb
module ParcelsHelper
end

app/views/parcels/_form.html.erb
<%= form_for [@auction, @parcel] do |f| %>
  <% if @parcel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parcel.errors.count, "error") %> prohibited this parcel from being saved:</h2>

      <ul>
      <% @parcel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :minimum_bid %><br />
    <%= f.text_field :minimum_bid %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %><br />
    <%= f.number_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parcels/edit.html.erb
<h1>Editing parcel</h1>

<%= render 'form' %>

<%= link_to 'Show', [@auction, @parcel] %> |
<%= link_to 'Back', auction_parcel_path %>

app/views/parcels/index.html.erb
<h1>Listing parcels</h1>

<table class="table table-striped">
  <tr>
    <th>Number</th>
    <th>Address</th>
    <th>City</th>
    <th>Country</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Minimum bid</th>
    <th>State</th>
    <th>Zip</th>
  </tr>

<% @parcels.each do |parcel| %>
  <tr>
    <td><%= parcel.number %></td>
    <td><%= parcel.address %></td>
    <td><%= parcel.city %></td>
    <td><%= parcel.country %></td>
    <td><%= parcel.latitude %></td>
    <td><%= parcel.longitude %></td>
    <td><%= parcel.minimum_bid %></td>
    <td><%= parcel.state %></td>
    <td><%= parcel.zip %></td>
    <td><%= link_to 'Show', auction_parcel_path(@auction, parcel), :class => "btn" %>
    <%= link_to 'Edit', edit_auction_parcel_path(@auction, parcel), :class => "btn" %>
    <%= link_to 'Destroy', auction_parcel_path(@auction,parcel), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Parcel', new_auction_parcel_path %>

<%= gmaps4rails(@json)%>

app/views/parcels/new.html.erb
<h1>New parcel</h1>

<%= render 'form' %>

<%= link_to 'Back', auction_parcel_path %>

app/views/parcels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @parcel.number %>
</p>

<p>
  <b>Address:</b>
  <%= @parcel.address %>
</p>

<p>
  <b>City:</b>
  <%= @parcel.city %>
</p>

<p>
  <b>Country:</b>
  <%= @parcel.country %>
</p>

<p>
  <b>Latitude:</b>
  <%= @parcel.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @parcel.longitude %>
</p>

<p>
  <b>Minimum bid:</b>
  <%= @parcel.minimum_bid %>
</p>

<p>
  <b>State:</b>
  <%= @parcel.state %>
</p>

<p>
  <b>Zillow parcel:</b>
  <%= @parcel.zillow_parcel %>
</p>

<p>
  <b>Zip:</b>
  <%= @parcel.zip %>
</p>



<%= link_to 'Edit', edit_auction_parcel_path(@auction, @parcel) %> |
<%= link_to 'Back', auction_parcels_path %>

<%=gmaps4rails(@json)%>