config/routes.rb
Test3::Application.routes.draw do

  resources :auctions do
     resources :parcels
  end

  match 'destroy_all_auctions' => 'auctions#destroy_all'

  devise_for :users

  devise_for :installs

  
  root :to => "home#index"

    
  
  

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  has_many :parcels
  attr_accessible :auction_date, :file_date, :auction_html_uploader, :auction_pdf_uploader, :id
  
  mount_uploader :auction_pdf_uploader, AuctionPdfUploader
  mount_uploader :auction_html_uploader, AuctionHtmlUploader
  

  
    
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @auctions }
    end
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
    @auction = Auction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @auction }
    end
  end

  # GET /auctions/new
  # GET /auctions/new.json
  def new
    @auction = Auction.new
    @auction.save

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @auction }
    end
  end

  # GET /auctions/1/edit
  def edit
    @auction = Auction.find(params[:id])
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(params[:auction])

    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render json: @auction, status: :created, location: @auction }
      else
        format.html { render action: "new" }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /auctions/1
  # PUT /auctions/1.json
  def update
    @auction = Auction.find(params[:id])

    respond_to do |format|
      if @auction.update_attributes(params[:auction])
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction = Auction.find(params[:id])
    @auction.destroy

    respond_to do |format|
      format.html { redirect_to auctions_url }
      format.json { head :no_content }
    end
  end
  
  def destroy_all
     @auctions = Auctions.all 
     @auctions.each { |p| p.destroy }
        
    respond_to do |format|
      format.html { redirect_to auctions_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_form.html.erb
<%= form_for @auction, :html => {:multipart => true} do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% @auction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_date %><br />
    <%= f.date_select :file_date %>
  </div>
  <div class="field">
    <%= f.label :auction_date %><br />
    <%= f.date_select :auction_date %>
  </div>
  <div class="field">
  	<%= f.label "Origional PDF File"%>
  	<%= f.file_field :auction_pdf_uploader%>
  </div>
  <div class="field">
  	<%= f.label "HTML File Created by PDF2HTML"%>
  	<%= f.file_field :auction_html_uploader%>

  </div>
  
  <div class="actions">
  	<br/>
    <%= f.submit :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/auctions/edit.html.erb
<h1>Editing auction</h1>

<%= render 'form' %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<section class="hero-unit"> 

<h2>Auctions</h2>

<p>These are the auction files published by Indianapolis / Marion County. We get them from <%=link_to('http://www.indy.gov/eGov/County/Comm/surplus/Pages/home.aspx', 'http://www.indy.gov/eGov/County/Comm/surplus/Pages/home.aspx') %> </p>
<p>We upload the PDF documents gotten from that website onto ours and also a HTML translation of the PDF document. We use our algorithm to parse that data into our database and then check it manually as PDF data parsing is mildly error prone. So far, the city has not yielded to our requests to make the data available in format more friendly to data processing, so please regard all data with a mild amount of suspicion until you can reference it back to the origional PDF document. </p>
<p>Thanks, and enjoy!</p>
<p></p>


</section>

<section>
<table class="table table-striped">
  <tr>
    <th>Pdf file</th>
    <th>Html file</th>
    <th>File date</th>
    <th>Auction date</th>
	<th>Parcels</th>
	<th>Actions</th>
    <th></th>
 
  </tr>

<% @auctions.each do |auction| %>
  <tr>
    <td><%= link_to auction.auction_pdf_uploader_url, auction.auction_pdf_uploader_url %></td>
    <td><%= link_to "test", '#' %></td>
    <td><%= auction.file_date %></td>
    <td><%= auction.auction_date %></td>
	<td><%= link_to "View Parcels (#{auction.parcels.count.to_s})", auction_parcels_path(auction)%>
    <td><%= link_to 'Show', auction, :class => 'btn btn-inverse' %>
    <%= link_to 'Edit', edit_auction_path(auction), :class => 'btn btn-inverse'%>
    <%= link_to 'Destroy', auction, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

</section>

<section>
<%= link_to 'New Auction', new_auction_path, :class => 'btn pull-right btn-primary' %>
<%= link_to 'Destroy All', destroy_all_auctions_path, method: :destroy_all, data: {confirm: 'Delete ALL auctions?'}, :class => 'btn btn-danger pull-right'%>
</section>

app/views/auctions/new.html.erb
<h1>New auction</h1>

<%= render 'form' %>

<%= link_to 'Back', auctions_path %>

app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pdf file:</b>
  <%= @auction.auction_pdf_uploader %>
</p>

<p>
  <b>Html file:</b>
  <%= @auction.auction_html_uploader %>
</p>

<p>
  <b>File date:</b>
  <%= @auction.file_date %>
</p>

<p>
  <b>Auction date:</b>
  <%= @auction.auction_date %>
</p>

<%= link_to "View Parcels (#{@auction.parcels.count})", auction_parcels_path(@auction) %> |

<%= link_to 'Edit', edit_auction_path(@auction) %> |
<%= link_to 'Back', auctions_path %>